### ISSUE TITLE
render target error on tvOS

### ISSUE THREAD

**Issue by rdouble** [keijiro/Skinner#5]
I tried to build for tvOS, and get this error:

```Objective-C
[MTLRenderPipelineDescriptorInternal validateWithDevice:], line 1659: error 'This set of render targets requires 48 bytes of pixel storage. This device supports 32 bytes.'

```

I was wondering if there is a way to get this to compile on tvOS, or if tvOS is unsupported.

**Comment by keijiro** [comment]
Are you trying to build the sample project included in this repository? I guess it doesn't work because of the PostProcessing stack -- it's using several high-bpp textures that are not available on mobile devices.

Instead of that, could you try to build the GlitchDancer project?

https://github.com/keijiro/GlitchDancer
https://twitter.com/_kzr/status/816629769408102401

GlitchDancer is carefully tweaked for iOS, so that it can keep 60fps on recent iOS devices. I wonder if it can keep 60fps on tvOS... please let me know results if you can make it run on a tvOS device.

**Comment by rdouble** [comment]
I have tried GlitchDancer on tvOS too, and get the same error. GlitchDancer does work on my iPhone SE, though.  The results from the Skinner demo are the same: works on iPhone, but not Apple TV.  

I am trying to figure out if I just need to change a build setting or throw in a Metal shader flag or if the Apple TV has specific hardware limitations causing this problem.  It's not high priority, I just wondered you knew of an obvious fix.  I'll keep looking into it and let you know if I figure it out.

**Comment by keijiro** [comment]
Thanks for the information. I'm a bit surprised because there shouldn't be big differences between iOS and tvOS according to the capabilities list.

https://developer.apple.com/metal/capabilities/

I'll look into it later. I think I can borrow a device from somewhere...

**Comment by keijiro** [comment]
I realized that UNITY_TVOS should be added to this ifdef condition.

https://github.com/keijiro/Skinner/commit/5a9b46c2d8a3fcc4ddc5749b6d1b12cc48bc5900

I've updated both the Skinner package and GlitchDancer. They must run on tvOS devices now.

**Comment by rdouble** [comment]
thanks! it works now
